version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: base-server
    ports:
      - "3002:3002"
    depends_on:
      - redis
      - postgres
    networks:
      - my-network
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379

    volumes:
      - .:/app
      - node_modules:/app/node_modules

  redis:
    image: redis
    container_name: redis-base-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my-network

  postgres:
    image: postgres
    container_name: postgresql-base-server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass1234
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
  node_modules:

networks:
  my-network:
